### ISSUE TITLE
TODO (help wanted)

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/ConstrainedOptim.jl#4]
Here's a list of things that I believe we should focus on next. If anyone is interested in helping out here that would be very much appreciated.

**Interface**

- [ ] Enable `value!` et al. for the constraints in NLSolversBase **top priority**
- [ ] Add a quasi-Newton algorithm
- [ ] Update MathProgBase interface
- [ ] Add a Newton-Krylov scheme

**Interior / IPNewton**

- [ ] Support sparse Hessian and sparse constraint Jacobian **top priority**
- [ ] Figure out how to enable the autodiff-tests in `constraints.jl` again
- [ ] Move "show_linesearch`  to Optim.options
- [ ] Rethink how to deal with `allow_f_increases` for constrained problems (it should "always" be allowed)
- [ ] There are lots of functions from Tim's PR that are not used anywhere. Figure out what to delete.

**Linesearch**

- [ ] Figure out how Tim inteded to use `backtrack_constrained` (only `backtrack_constrained_grad` works at the moment)
- [ ] Move line searches to LineSearches.jl (after we change the interface in LineSearches)

**Testing**

- [ ] Add more constrained optimization tests to OptimTestProblems
- [ ] Update OptimTests to work with ConstrainedOptim (We need sparse Hessian + Jacobian support before going all in on CUTEst problems)
- [ ] Compare against Ipopt

**Comment by cortner** [comment]
instead of quasi-newton how about a Newton-Krylov scheme? Should be easier to build into the current code.

**Comment by pkofod** [comment]
> instead of quasi-newton how about a Newton-Krylov scheme? Should be easier to build into the current code.

That would be interesting as well, sure.

**Comment by anriseth** [comment]
> instead of quasi-newton how about a Newton-Krylov scheme? Should be easier to build into the current code.

To clarify, do you mean supporting "Hessian-free" (Hessian-vector) type Newton-Krylov, or to support, for example, `IterativeSolvers.jl`? I have only dealt with Newton-Krylov in the context of nonlinear equations, where it can also mean that you use some iterative solver for the problem (Jacobian*dx = Residual), regardless of whether the Jacobian is assembled or not.

**Comment by cortner** [comment]
In A NK scheme you can replace the hxv with finite differences- that is the advantage for me

**Comment by anriseth** [comment]
I've added Newton-Krylov to the list :)

**Comment by gragusa** [comment]
I will start updating the MathProgBase interface.

**Comment by anriseth** [comment]
> I will start updating the MathProgBase interface.

Thanks for doing that, @gragusa :) Note that we have added the `IPNewton` code from this repository to `Optim` now, so I think you should be able to update the interface with using `Optim` instead of `ConstrainedOptim`. Ref https://github.com/JuliaNLSolvers/Optim.jl/pull/608 https://github.com/JuliaNLSolvers/Optim.jl/issues/609 

I also see that the JuliaOpt group have started implementing the solver interfaces with MathOptInterface now, as they are planning to move away from MathProgBase (Refs https://github.com/JuliaOpt/Ipopt.jl/pull/108 https://github.com/JuliaOpt/Ipopt.jl/pull/116).
I don't know whether it is more complicated to interface to MOI and therefore less time consuming to do this for MPB, but it seems like MOI is the future.

**Comment by JMmontilla** [comment]
Could a [SQP](https://en.wikipedia.org/wiki/Sequential_quadratic_programming) method be implemented as well? I use it in the [NLOpt](https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#slsqp) suite and is the one that works best for me in general. I would like to help and try to implement it myself, but I have a lot to learn of Julia before. Aside from that this package is great :), will probably use it.

**Comment by pkofod** [comment]
Yes, SQP methods are certainly on the table. Notice that his functionality is now in Optim.jl :)
